language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: fTu+GDB/F1ToODLEAkKuC9EV9jDReNR6zbev4zNuoJWvZmpdcBTVmohfMpUSf6GNqdtLPQ9Q7kLWfHFMNfCqLtKvbvT1+nAPu/Lm8bKZoPwq6vLDlMrVE0T8J/b+3kcSa09hUD6fZQv2UOdSR4m51+ItoYuSC/Zu+qW/6+rEM+koYNwnqfp7MvMOIHUZd40cKgps2TF2PtZGCKqrA+2t6or4nu9D81HDUtoIqFzwxdkRpjfjfemTCGF12N6h8PfJ0uSCskx5kBa2VKDj9oOvEHkebjIsCNMBOSXWwCMgYcPoU2+xyn+UmjDcCxvlyYFli7iDKwAOnaKjyB8dPEgRnx3s+5PhDHn/WmB0zmQaZm1TRYtBhD/xwM/wPOc/Ks9XodYOQ8ayWlf8l+Os7QL7QNDD/ErymvQi4bJ8I+Mnq4Gtm1qd4Xz1UmU52nSgMe9jYckTL/4sq2D9oEloczkKFBYy3fT5t4K7+WPIk0zzeOouNOaPmP8+Uf959eBIC6IRrWvHuH9/zPic1imUQywRwwMl9093PhcoFlfYqYTtIBIyECn3VVLFgwM0GNP6PF9bbCLZDvBNkhwFhDF+4NEfZCISggiOqoB+nMiJ8LF2vFYv7rMRLxch7bv/3Sz8JDx4K0nEldLJTW/QqCEUA16fr3gulwnGGxfp9aMWGdyV5f0=
